;; Skills
/def -F -p99 -PhCyellow -mregexp -t'Shield Usage:'
/def -F -p99 -PhCyellow -mregexp -t'Leather Armor:'
/def -F -p99 -PhCyellow -mregexp -t'Light Chain:'
/def -F -p99 -PhCyellow -mregexp -t'Heavy Chain:'
/def -F -p99 -PhCyellow -mregexp -t'Light Plate:'
/def -F -p99 -PhCyellow -mregexp -t'Heavy Plate:'
/def -F -p99 -PhCyellow -mregexp -t'Parry Ability:'
/def -F -p99 -PhCyellow -mregexp -t'Multi Opponent:'
/def -F -p99 -PhCyellow -mregexp -t'Light Edged:'
/def -F -p99 -PhCyellow -mregexp -t'Medium Edged:'
/def -F -p99 -PhCyellow -mregexp -t'Heavy Edged:'
/def -F -p99 -PhCyellow -mregexp -t'Twohanded Edged:'
/def -F -p99 -PhCyellow -mregexp -t'Light Blunt:'
/def -F -p99 -PhCyellow -mregexp -t'Medium Blunt:'
/def -F -p99 -PhCyellow -mregexp -t'Large Blunt:'
/def -F -p99 -PhCyellow -mregexp -t'Twohanded Blunt:'
/def -F -p99 -PhCyellow -mregexp -t'Slings:'
/def -F -p99 -PhCyellow -mregexp -t'Staff Sling:'
/def -F -p99 -PhCyellow -mregexp -t'Short Bow:'
/def -F -p99 -PhCyellow -mregexp -t'Long Bow:'
/def -F -p99 -PhCyellow -mregexp -t'Composite Bow:'
/def -F -p99 -PhCyellow -mregexp -t'Light Crossbow:'
/def -F -p99 -PhCyellow -mregexp -t'Heavy Crossbow:'
/def -F -p99 -PhCyellow -mregexp -t'Short Staff:'
/def -F -p99 -PhCyellow -mregexp -t'Quarter Staff:'
/def -F -p99 -PhCyellow -mregexp -t'Pikes:'
/def -F -p99 -PhCyellow -mregexp -t'Halberds:'
/def -F -p99 -PhCyellow -mregexp -t'Light Thrown:'
/def -F -p99 -PhCyellow -mregexp -t'Heavy Thrown:'
/def -F -p99 -PhCyellow -mregexp -t'Brawling:'
/def -F -p99 -PhCyellow -mregexp -t'Primary Magic:'
/def -F -p99 -PhCyellow -mregexp -t'Harness Ability:'
/def -F -p99 -PhCyellow -mregexp -t'Power Perceive:'
/def -F -p99 -PhCyellow -mregexp -t'Magical Devices:'
/def -F -p99 -PhCyellow -mregexp -t'Targeted Magic:'
/def -F -p99 -PhCyellow -mregexp -t'Evasion:'
/def -F -p99 -PhCyellow -mregexp -t'Climbing:'
/def -F -p99 -PhCyellow -mregexp -t'Perception:'
/def -F -p99 -PhCyellow -mregexp -t'Tracking:'
/def -F -p99 -PhCyellow -mregexp -t'Scouting:'
/def -F -p99 -PhCyellow -mregexp -t'Hiding:'
/def -F -p99 -PhCyellow -mregexp -t'Lockpicking:'
/def -F -p99 -PhCyellow -mregexp -t'Disarm Traps:'
/def -F -p99 -PhCyellow -mregexp -t'Stalking:'
/def -F -p99 -PhCyellow -mregexp -t'Stealing:'
/def -F -p99 -PhCyellow -mregexp -t'First Aid:'
/def -F -p99 -PhCyellow -mregexp -t'Foraging:'
/def -F -p99 -PhCyellow -mregexp -t'Escaping:'
/def -F -p99 -PhCyellow -mregexp -t'Backstab:'
/def -F -p99 -PhCyellow -mregexp -t'Skinning:'
/def -F -p99 -PhCyellow -mregexp -t'Swimming:'
/def -F -p99 -PhCyellow -mregexp -t'Scholarship:'
/def -F -p99 -PhCyellow -mregexp -t'Mechanical Lore:'
/def -F -p99 -PhCyellow -mregexp -t'Musical Theory:'
/def -F -p99 -PhCyellow -mregexp -t'Appraisal:'
/def -F -p99 -PhCyellow -mregexp -t'Teaching:'
/def -F -p99 -PhCyellow -mregexp -t'Trading:'
/def -F -p99 -PhCyellow -mregexp -t'Animal Lore:'
/def -F -p99 -PhCyellow -mregexp -t'Percussion:'
/def -F -p99 -PhCyellow -mregexp -t'Strings:'
/def -F -p99 -PhCyellow -mregexp -t'Winds:'
/def -F -p99 -PhCyellow -mregexp -t'Vocals:'
/def -F -p99 -PhCyellow -mregexp -t'Transference:'
/def -F -p99 -PhCyellow -mregexp -t'Astrology:'
/def -F -p99 -PhCyellow -mregexp -t'Empathy:'
/def -F -p99 -PhCred -mregexp -t'mind lock'
/def -F -p99 -ahCcyan -mregexp -t'SKILL:.*'


;;; Other stuff.

/def -F -ahCyellow -mregexp -t'^Obvious paths:.*'
/def -F -ahCyellow -mregexp -t'^Obvious exits:.*'
/def -F -ahCmagenta -mregexp -t'^\[.*\]'

/def -p100 -ahuBCmagenta -mregexp -t'^A .* notices you trying to stalk it.'

/def -F -PhCyellow -mregexp -t'[ ][Yy]ou[\. ]'
/def -F -PhCyellow -mregexp -t'^[Yy]ou[\. ]'
/def -p100 -PhCcyan -mregexp -t'^You whisper to [A-Za-z]+'
/def -p99 -PhCgreen -mregexp -t'^You [A-Za-z]*[ ]*say,'
/def -p99 -PhCgreen -mregexp -t'^You [A-Za-z]*[ ]*hiss,'
/def -p99 -PhCgreen -mregexp -t'^You [A-Za-z]*[ ]*say in [A-Za-z]+,'
/def -p99 -PhCgreen -mregexp -t'^You [A-Za-z]*[ ]*ask,'
/def -p99 -PhCgreen -mregexp -t'^You [A-Za-z]*[ ]*ask in [A-Za-z]+,'
/def -p99 -PhCgreen -mregexp -t'^You [A-Za-z]*[ ]*exclaim,'
/def -p99 -PhCgreen -mregexp -t'^You [A-Za-z]*[ ]*exclaim in [A-Za-z]+,'
/def -p99 -PhCgreen -mregexp -t'You belt out,'
/def -p99 -F -PhCgreen -mregexp -t'^You hear the voice of [A-Za-z]+ [A-Za-z]+, '
/def -p99 -F -PhCgreen -mregexp -t'^You hear the voice of [A-Za-z]+ [A-Za-z]+ in [A-Za-z]+, '
/def -p99 -F -PhCyellow -mregexp -t'^Your mind hears [A-Za-z]+ thinking, '
/def -p99 -F -PhCgreen -mregexp -t'^You hear the ghostly voice of [A-Za-z]+ [A-Za-z]+, '
/def -p100 -ahBCcyan -mregexp -t'^You have no significant injuries.'
/def -ahCred -mregexp -t'touches you'
/def -F -PhCgreen -mregexp -t'No Ranger stands alone'
/def -F -PhCgreen -mregexp -t'No ranger stands alone'

/def -F -ahCred -mregexp -t'^The bandages binding your.*'
/def -F -ahCmagenta -mregexp -t'You\'ve gained a new rank in.*'
/def -F -ahCbgred -mregexp -t'^You think you have your best shot possible now.'
/def -F -PhCcyan -mregexp -t'^Also in room: '
/def -F -PhCcyan -mregexp -t'^Also in the room: '
/def -F -PhCcyan -mregexp -t'^Also here: '
/def -F -PhBCgreen -p99 -mregexp -t'^[A-Za-z]+[ ]*[A-Za-z]* growls, '
/def -F -PhBCgreen -p99 -mregexp -t'^[A-Za-z]+[ ]*[A-Za-z]* hisses, '
/def -F -PhBCgreen -p99 -mregexp -t'^[A-Za-z]+[ ]*[A-Za-z]* says, '
/def -F -PhBCgreen -p99 -mregexp -t'^[A-Za-z]+[ ]*[A-Za-z]* says to [A-Za-z]+, '
/def -F -PhBCgreen -p99 -mregexp -t'^[A-Za-z]+[ ]*[A-Za-z]* says in [A-Za-z]+, '
/def -F -PhBCgreen -p99 -mregexp -t'^[A-Za-z]+[ ]*[A-Za-z]* asks, ' 
/def -F -PhBCgreen -p99 -mregexp -t'^[A-Za-z]+[ ]*[A-Za-z]* asks [A-Za-z]+, ' 
/def -F -PhBCgreen -p99 -mregexp -t'^[A-Za-z]+[ ]*[A-Za-z]* asks in [A-Za-z]+, ' 
/def -F -PhBCgreen -p99 -mregexp -t'^[A-Za-z]+[ ]*[A-Za-z]* exclaims, '
/def -F -PhBCgreen -p99 -mregexp -t'^[A-Za-z]+[ ]*[A-Za-z]* exclaims in [A-Za-z]+, '
/def -F -PhBCgreen -p99 -mregexp -t'^[A-Za-z]+[ ]*[A-Za-z]* yells, '
/def -F -PhBCgreen -p99 -mregexp -t'^[A-Za-z]+[ ]*[A-Za-z]* yells in [A-Za-z]+, '
/def -F -PhBCgreen -p99 -mregexp -t'^From all around you a voice echoes, '
/def -F -PhBCcyan -p99 -mregexp -t'^[A-Za-z]+ whispers, '
/def -F -PhBCcyan -p99 -mregexp -t'^[A-Za-z]+ whispers to your group, '
/def -F -PhBCgreen -p99 -mregexp -t'^You hear [A-Za-z]+ yell, ' 
/def -F -PhBCgreen -p99 -mregexp -t'^From the darkness [A-Za-z]* says'
/def -F -PhBCgreen -p99 -mregexp -t'^Into the darkness you say'
/def -F -PhBCgreen -p99 -mregexp -t'^Into the darkness you ask'

/def -F -ahCyellow -p99 -mregexp -t'^The [A-Za-z]+ advance towards you'
/def -F -ahBCred -p99 -mregexp -t'^The .* closes to [A-Za-z]+ range on you'
/def -F -ahBCred -p99 -mregexp -t'^A .* closes to [A-Za-z]+ range on you'
/def -F -ahBCred -p99 -mregexp -t'^An .* closes to [A-Za-z]+ range on you'
/def -F -ahBCred -p99 -mregexp -t'^You close to [A-Za-z]+ range on the .*'

